services:

  sqlite:
    image: suriya08/sqlite3:1.0.3
    container_name: sqlite
    volumes:
      - ./database:/app/data  # Mount a directory for SQLite databases
    ports:
      - "8191:8191"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    volumes:
      - ./data:/db

  minio:
    image: 'minio/minio:latest'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "8900:8900"
    volumes:
      - 'minio:/data/minio'
    command: 'minio serve /data/minio --console-address ":8900"'

volumes:
  data:
  minio:
    driver: local
